[package]
name = "oandx"
version = "0.1.0"
edition = "2021"
description = "O and X game"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.13", features = ["derive"] }
rand = "0.8.3"